### ISSUE TITLE
使用kotlin编写会简单很多

### ISSUE THREAD

**Issue by feisher** [codyer/ElegantBus#1]

**Comment by codyer** [comment]
你说的是对的，感谢你的建议，kotlin写的代码本身就会比java更简单。
那为什么我用的是Java呢？
其实基于以下两点考虑：
1、Java我更熟悉，更能对此库的质量进行保证。
2、现在Kotlin的普及并不是100%，如果使用Kotlin实现，会对Java项目使用者造成一定困扰。但是用Java实现却不会对Kotlin项目造成困扰。
以上，如果有兴趣，欢迎一起使用Kotlin开发一个新的分支。

**Comment by feisher** [comment]
@@//kotlin简单案例代码（第一种方案的，，虽说有好几个缺陷，但基本满足常见项目使用了）
```kotlin
object AppVM: ViewModel(){
    val data = MutableLiveData<String>()
    val update = MutableLiveData<UpdateApk>()
}
class UpdateApk( var updateApk :Boolean  = false)
```

//使用方法
1.发送  AppVM.update.postValue(UpdateApk())
2.接收  AppVM.update.observe(this,Observer{
	//做受到广播需要处理的业务
})  
@codyer

**Comment by codyer** [comment]
是的，Kotlin我也有用到，代码本身就更简洁，给我们开发者带来了更多的便利。
LiveData本身就是发布订阅模式，简单项目确实可以直接使用LivaData就能实现基本的事件发布订阅了。
此库的作用更多的是做一个统一管理，以及本身LivaData作为事件总线时，存在的几个问题的解决吧。
