### ISSUE TITLE
粘性事件

### ISSUE THREAD

**Issue by 15615833080** [codyer/ElegantBus#10]
用observeSticky关联生命周期接收sticky事件，每次创建都会接收到，可以设置接收一次事件就清掉那个sticky事件吗？

**Comment by codyer** [comment]
> 用observeSticky关联生命周期接收sticky事件，每次创建都会接收到，可以设置接收一次事件就清掉那个sticky事件吗？

能详细描述一下你的需求吗？

按照你的描述，我理解的是你想实现某个事件A发送了一个VALID的值的事件，当接收到后可以在发送一个INVALID事件冲掉那个有VALID的值，在你的逻辑里判断是否收到的事件是VALID，这样就实现了既有sticky能力，又不会在多个地方执行重复操作。

代码类似如下：
        public static Integer VALID = 1;
        public static Integer INVALID = -1;
        TestScopeBus.eventInt().post(VALID);// sticky事件被发送

// 监听事件
        TestScopeBus.eventInt().observeSticky(owner, new ObserverWrapper<Integer>() {
            @Override
            public void onChanged(final Integer value) {
                if(VALID.equals(value)){
                    TestScopeBus.eventInt().setValue(INVALID);// 重置事件
                    TestScopeBus.eventInt().removeObserver(this);//移除监听，保证收到这一次VALID就不再接收事件变化了
                    // TODO some logic
                      doSomeThing();
                }
            }
        });

**Comment by 15615833080** [comment]
感谢回复，我期望的是，粘性事件只保存最近的一次。比如 post（a）之后，再post（b），我期望只收到b这个值。而不会收到a。a和b都不是固定的，无法进行判断。
如eventbus中：eventbus的粘性事件保留的是最新值，而不是所有值
保留最新值。您可以使用粘性事件，而不是实现自己的缓存。因此，EventBus会将特定类型的最后一个粘性事件保留在内存中。然后，粘性事件可以传递给订阅者或明确查询

**Comment by codyer** [comment]
> 感谢回复，我期望的是，粘性事件只保存最近的一次。比如 post（a）之后，再post（b），我期望只收到b这个值。而不会收到a。a和b都不是固定的，无法进行判断。
> 如eventbus中：eventbus的粘性事件保留的是最新值，而不是所有值
> 保留最新值。您可以使用粘性事件，而不是实现自己的缓存。因此，EventBus会将特定类型的最后一个粘性事件保留在内存中。然后，粘性事件可以传递给订阅者或明确查询

正常就是不会收到a，除非你是在b发送之前就注册了，否则b是会覆盖a的，目前并没有说实现自己的缓存，只会保留最后一个值的，这个是由livedata默认方式实现的。

**Comment by codyer** [comment]
> 用observeSticky关联生命周期接收sticky事件，每次创建都会接收到，可以设置接收一次事件就清掉那个sticky事件吗？

2.2.2版本新增了设置屏障，间接实现清除sticky事件的效果，如果你还需要这种case可以使用新的版本
