### ISSUE TITLE
泛型支持

### ISSUE THREAD

**Issue by zguop** [codyer/ElegantBus#11]
大佬 支持一下这样的方法
  public static <> Observable<T> get(@NonNull String key) {
        return (Observable<T>) get(key, Object.class);
    }

 val observable: Observable<List<String>> = LiveEventBus.get("KEY_TEST_OBSERVE_FOREVER")

可否改一下
   public static LiveDataWrapper<Object> getDefault(String event) {
        return getDefault(event, Object.class);
    }
![image](https://user-images.githubusercontent.com/16206793/126994629-6dbed047-c7be-45ac-867a-7388b13c7919.png)

**Comment by codyer** [comment]
> 大佬 支持一下这样的方法
> public static <> Observable get(@nonnull String key) {
> return (Observable) get(key, Object.class);
> }
> 
> val observable: Observable<List> = LiveEventBus.get("KEY_TEST_OBSERVE_FOREVER")
> 
> 可否改一下
> public static LiveDataWrapper getDefault(String event) {
> return getDefault(event, Object.class);
> }
> ![image](https://user-images.githubusercontent.com/16206793/126994629-6dbed047-c7be-45ac-867a-7388b13c7919.png)

没明白是要做什么？能描述下需求场景吗？

**Comment by zguop** [comment]
传递List或者Pair<Boolean, Double>这种泛型对象

 LiveDataWrapper<List<String>> aDefault = getDefault()这样

![image](https://user-images.githubusercontent.com/16206793/127108980-2a459875-8969-4833-9e80-3b93b3dfdd98.png)

**Comment by codyer** [comment]
2.2.1版本已经支持泛型

**Comment by zguop** [comment]
???代码好像没啥变化唉
2.2.1

**Comment by codyer** [comment]
> ???代码好像没啥变化唉
> 2.2.1

已经可以定义泛型了的

    @Event(value = "eventBean 事件测试", multiProcess = true)
    List<String> eventList;

    @Event(value = "eventMap 泛型测试", multiProcess = true)
    Map<String, List<String>> eventMap;

这种都支持的，可以看下我的另一个示例仓库

**Comment by zguop** [comment]
> > ???代码好像没啥变化唉
> > 2.2.1
> 
> 已经可以定义泛型了的
> 
> ```
> @Event(value = "eventBean 事件测试", multiProcess = true)
> List<String> eventList;
> 
> @Event(value = "eventMap 泛型测试", multiProcess = true)
> Map<String, List<String>> eventMap;
> ```
> 
> 这种都支持的，可以看下我的另一个示例仓库

那个。我没有去使用用注解生成，因为这个注解也就是帮我们调用ElegantBus，而且不编译不会生成代码，还有...就是麻烦，感觉没必要哈 ，那个代码上能直接支持么

**Comment by codyer** [comment]
> > > ???代码好像没啥变化唉
> > > 2.2.1
> > 
> > 
> > 已经可以定义泛型了的
> > ```
> > @Event(value = "eventBean 事件测试", multiProcess = true)
> > List<String> eventList;
> > 
> > @Event(value = "eventMap 泛型测试", multiProcess = true)
> > Map<String, List<String>> eventMap;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这种都支持的，可以看下我的另一个示例仓库
> 
> 那个。我没有去使用用注解生成，因为这个注解也就是帮我们调用ElegantBus，而且不编译不会生成代码，还有...就是麻烦，感觉没必要哈 ，那个代码上能直接支持么

朋友，你可以看下我的使用说明，为什么推荐使用注解生成，而不直接使用，你说的那种方式是不能保证事件管理的，容易出现类型转换错误和同名覆盖问题，还有，编译生成代码这个不要排斥，这个是很多成熟库常用方式。而且你要对泛型使用和泛型擦除抱有警惕性哦，不然容易踩坑的。

**Comment by zguop** [comment]
> > > > ???代码好像没啥变化唉
> > > > 2.2.1
> > > 
> > > 
> > > 已经可以定义泛型了的
> > > ```
> > > @Event(value = "eventBean 事件测试", multiProcess = true)
> > > List<String> eventList;
> > > 
> > > @Event(value = "eventMap 泛型测试", multiProcess = true)
> > > Map<String, List<String>> eventMap;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这种都支持的，可以看下我的另一个示例仓库
> > 
> > 
> > 那个。我没有去使用用注解生成，因为这个注解也就是帮我们调用ElegantBus，而且不编译不会生成代码，还有...就是麻烦，感觉没必要哈 ，那个代码上能直接支持么
> 
> 朋友，你可以看下我的使用说明，为什么推荐使用注解生成，而不直接使用，你说的那种方式是不能保证事件管理的，容易出现类型转换错误和同名覆盖问题，还有，编译生成代码这个不要排斥，这个是很多成熟库常用方式。而且你要对泛型使用和泛型擦除抱有警惕性哦，不然容易踩坑的。

没必要一味的追求注解生成，也不是说用了注解就很成熟了，主要还是看场景。个人认为这个库实在没必要用你说的这个注解管理= ，= 你这边注解可以也行，但是希望是代码上也支持一下呗？？也不是不行嘛？

在一个工具类里定义好所有事件，跟你所说的注解管理，，不就能达到同样的目的吗？？我记得当时一开始我是用了的 但看了生成的代码，跟我写个工具类好像没什么区别（这里我有点忘记了），为什么还要多此一举呢？

**Comment by codyer** [comment]
> > > > > ???代码好像没啥变化唉
> > > > > 2.2.1
> > > > 
> > > > 
> > > > 已经可以定义泛型了的
> > > > ```
> > > > @Event(value = "eventBean 事件测试", multiProcess = true)
> > > > List<String> eventList;
> > > > 
> > > > @Event(value = "eventMap 泛型测试", multiProcess = true)
> > > > Map<String, List<String>> eventMap;
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 这种都支持的，可以看下我的另一个示例仓库
> > > 
> > > 
> > > 那个。我没有去使用用注解生成，因为这个注解也就是帮我们调用ElegantBus，而且不编译不会生成代码，还有...就是麻烦，感觉没必要哈 ，那个代码上能直接支持么
> > 
> > 
> > 朋友，你可以看下我的使用说明，为什么推荐使用注解生成，而不直接使用，你说的那种方式是不能保证事件管理的，容易出现类型转换错误和同名覆盖问题，还有，编译生成代码这个不要排斥，这个是很多成熟库常用方式。而且你要对泛型使用和泛型擦除抱有警惕性哦，不然容易踩坑的。
> 
> 没必要一味的追求注解生成，也不是说用了注解就很成熟了，主要还是看场景。个人认为这个库实在没必要用你说的这个注解管理= ，= 你这边注解可以也行，但是希望是代码上也支持一下呗？？也不是不行嘛？
> 
> 在一个工具类里定义好所有事件，跟你所说的注解管理，，不就能达到同样的目的吗？？我记得当时一开始我是用了的 但看了生成的代码，跟我写个工具类好像没什么区别（这里我有点忘记了），为什么还要多此一举呢？

生成的就是一个工具类，如果你觉得自己写的更好，可以直接不用注解，注解生成的工具类可以实现泛型的效果，那你也可以，core里面的方法是支持你所说的泛型的。不懂你为什么会觉得不支持。自动生成的都可以实现。

**Comment by zguop** [comment]
> > > > > > ???代码好像没啥变化唉
> > > > > > 2.2.1
> > > > > 
> > > > > 
> > > > > 已经可以定义泛型了的
> > > > > ```
> > > > > @Event(value = "eventBean 事件测试", multiProcess = true)
> > > > > List<String> eventList;
> > > > > 
> > > > > @Event(value = "eventMap 泛型测试", multiProcess = true)
> > > > > Map<String, List<String>> eventMap;
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 这种都支持的，可以看下我的另一个示例仓库
> > > > 
> > > > 
> > > > 那个。我没有去使用用注解生成，因为这个注解也就是帮我们调用ElegantBus，而且不编译不会生成代码，还有...就是麻烦，感觉没必要哈 ，那个代码上能直接支持么
> > > 
> > > 
> > > 朋友，你可以看下我的使用说明，为什么推荐使用注解生成，而不直接使用，你说的那种方式是不能保证事件管理的，容易出现类型转换错误和同名覆盖问题，还有，编译生成代码这个不要排斥，这个是很多成熟库常用方式。而且你要对泛型使用和泛型擦除抱有警惕性哦，不然容易踩坑的。
> > 
> > 
> > 没必要一味的追求注解生成，也不是说用了注解就很成熟了，主要还是看场景。个人认为这个库实在没必要用你说的这个注解管理= ，= 你这边注解可以也行，但是希望是代码上也支持一下呗？？也不是不行嘛？
> > 在一个工具类里定义好所有事件，跟你所说的注解管理，，不就能达到同样的目的吗？？我记得当时一开始我是用了的 但看了生成的代码，跟我写个工具类好像没什么区别（这里我有点忘记了），为什么还要多此一举呢？
> 
> 生成的就是一个工具类，如果你觉得自己写的更好，可以直接不用注解，注解生成的工具类可以实现泛型的效果，那你也可以，core里面的方法是支持你所说的泛型的。不懂你为什么会觉得不支持。自动生成的都可以实现。

是的 我是参照你生成的工具 自己写的工具类来管理的，很不错。core里的方法 一定要传一个classType 没有定义不传的哦
![image](https://user-images.githubusercontent.com/16206793/129483251-1451105a-a99c-4ea2-aa1c-d31c68116e56.png)
类似这种 
其实我已经写好了这样的方法了。 希望在库里也支持一下 哈哈

**Comment by codyer** [comment]
> > > > > > > ???代码好像没啥变化唉
> > > > > > > 2.2.1
> > > > > > 
> > > > > > 
> > > > > > 已经可以定义泛型了的
> > > > > > ```
> > > > > > @Event(value = "eventBean 事件测试", multiProcess = true)
> > > > > > List<String> eventList;
> > > > > > 
> > > > > > @Event(value = "eventMap 泛型测试", multiProcess = true)
> > > > > > Map<String, List<String>> eventMap;
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 这种都支持的，可以看下我的另一个示例仓库
> > > > > 
> > > > > 
> > > > > 那个。我没有去使用用注解生成，因为这个注解也就是帮我们调用ElegantBus，而且不编译不会生成代码，还有...就是麻烦，感觉没必要哈 ，那个代码上能直接支持么
> > > > 
> > > > 
> > > > 朋友，你可以看下我的使用说明，为什么推荐使用注解生成，而不直接使用，你说的那种方式是不能保证事件管理的，容易出现类型转换错误和同名覆盖问题，还有，编译生成代码这个不要排斥，这个是很多成熟库常用方式。而且你要对泛型使用和泛型擦除抱有警惕性哦，不然容易踩坑的。
> > > 
> > > 
> > > 没必要一味的追求注解生成，也不是说用了注解就很成熟了，主要还是看场景。个人认为这个库实在没必要用你说的这个注解管理= ，= 你这边注解可以也行，但是希望是代码上也支持一下呗？？也不是不行嘛？
> > > 在一个工具类里定义好所有事件，跟你所说的注解管理，，不就能达到同样的目的吗？？我记得当时一开始我是用了的 但看了生成的代码，跟我写个工具类好像没什么区别（这里我有点忘记了），为什么还要多此一举呢？
> > 
> > 
> > 生成的就是一个工具类，如果你觉得自己写的更好，可以直接不用注解，注解生成的工具类可以实现泛型的效果，那你也可以，core里面的方法是支持你所说的泛型的。不懂你为什么会觉得不支持。自动生成的都可以实现。
> 
> 是的 我是参照你生成的工具 自己写的工具类来管理的，很不错。core里的方法 一定要传一个classType 没有定义不传的哦
> ![image](https://user-images.githubusercontent.com/16206793/129483251-1451105a-a99c-4ea2-aa1c-d31c68116e56.png)
> 类似这种
> 其实我已经写好了这样的方法了。 希望在库里也支持一下 哈哈

这种写法其实是有问题的，你可以去了解一下泛型擦除，这种方式我说过会出现类型强转问题哦，试想一下，有两个定义相同但是类型不同的事件，这时候其实都是可以接收到的，你做强转其实就会报错的哦～

**Comment by zguop** [comment]
懂都是懂，这种东西错误就让开发者处理吧 https://github.com/JeremyLiao/LiveEventBus 参考下这个

**Comment by zguop** [comment]
> > > > > > > > ???代码好像没啥变化唉
> > > > > > > > 2.2.1
> > > > > > > 
> > > > > > > 
> > > > > > > 已经可以定义泛型了的
> > > > > > > ```
> > > > > > > @Event(value = "eventBean 事件测试", multiProcess = true)
> > > > > > > List<String> eventList;
> > > > > > > 
> > > > > > > @Event(value = "eventMap 泛型测试", multiProcess = true)
> > > > > > > Map<String, List<String>> eventMap;
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > 这种都支持的，可以看下我的另一个示例仓库
> > > > > > 
> > > > > > 
> > > > > > 那个。我没有去使用用注解生成，因为这个注解也就是帮我们调用ElegantBus，而且不编译不会生成代码，还有...就是麻烦，感觉没必要哈 ，那个代码上能直接支持么
> > > > > 
> > > > > 
> > > > > 朋友，你可以看下我的使用说明，为什么推荐使用注解生成，而不直接使用，你说的那种方式是不能保证事件管理的，容易出现类型转换错误和同名覆盖问题，还有，编译生成代码这个不要排斥，这个是很多成熟库常用方式。而且你要对泛型使用和泛型擦除抱有警惕性哦，不然容易踩坑的。
> > > > 
> > > > 
> > > > 没必要一味的追求注解生成，也不是说用了注解就很成熟了，主要还是看场景。个人认为这个库实在没必要用你说的这个注解管理= ，= 你这边注解可以也行，但是希望是代码上也支持一下呗？？也不是不行嘛？
> > > > 在一个工具类里定义好所有事件，跟你所说的注解管理，，不就能达到同样的目的吗？？我记得当时一开始我是用了的 但看了生成的代码，跟我写个工具类好像没什么区别（这里我有点忘记了），为什么还要多此一举呢？
> > > 
> > > 
> > > 生成的就是一个工具类，如果你觉得自己写的更好，可以直接不用注解，注解生成的工具类可以实现泛型的效果，那你也可以，core里面的方法是支持你所说的泛型的。不懂你为什么会觉得不支持。自动生成的都可以实现。
> > 
> > 
> > 是的 我是参照你生成的工具 自己写的工具类来管理的，很不错。core里的方法 一定要传一个classType 没有定义不传的哦
> > ![image](https://user-images.githubusercontent.com/16206793/129483251-1451105a-a99c-4ea2-aa1c-d31c68116e56.png)
> > 类似这种
> > 其实我已经写好了这样的方法了。 希望在库里也支持一下 哈哈
> 
> 这种写法其实是有问题的，你可以去了解一下泛型擦除，这种方式我说过会出现类型强转问题哦，试想一下，有两个定义相同但是类型不同的事件，这时候其实都是可以接收到的，你做强转其实就会报错的哦～

这种类型问题让开发者处理吧。 T的默认就是Object
