### ISSUE TITLE
@EventGroup 问题

### ISSUE THREAD

**Issue by AngelRiven** [codyer/ElegantBus#12]
如果采用@EventGroup注解的方式，那岂不是每次添加一个新的消息，都要重新编译一下才能用这个消息。这样显然非常不方便呀。

**Comment by AngelRiven** [comment]
而且这种方式也适用于组件化场景，消息必须定义在一个公共包里

**Comment by codyer** [comment]
> 如果采用@eventgroup注解的方式，那岂不是每次添加一个新的消息，都要重新编译一下才能用这个消息。这样显然非常不方便呀。

这个是必然的，而且AS编译不都是无感的吗？使用注解方式当然要编译才生成，如果觉得不方便可以不使用注解方式，同样可以用，注解只是减少手工代码量，避免手写容易出错问题
