### ISSUE TITLE
多进程一定能拿到发送方的class吗

### ISSUE THREAD

**Issue by AngelRiven** [codyer/ElegantBus#13]

**Comment by AngelRiven** [comment]
ElegantBus.getDefault(String group, String event, Class<T> type, boolean multiProcess);
这个在多进程或者多APP发送的时候，最后通过class来转化json，一定能拿到class吗

**Comment by codyer** [comment]
> ElegantBus.getDefault(String group, String event, Class type, boolean multiProcess); 这个在多进程或者多APP发送的时候，最后通过class来转化json，一定能拿到class吗

没有理解你的问题是什么，请详细描述一下问题，以及出现问题的场景
