### ISSUE TITLE
高级特性里面的事件定义方式，怎么使用粘性事件，怎么取消注册常驻事件

### ISSUE THREAD

**Issue by LEOctivian** [codyer/ElegantBus#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by codyer** [comment]
高级特性是对事件统一进行管理的工具，粘性事件和常驻事件取消注册和常规用法一致。
ObserverWrapper 构造的时候可以设置是否sticky
常驻事件需要保留ObserverWrapper引用，取消的时候调用就行
