### ISSUE TITLE
项目运行不起来

### ISSUE THREAD

**Issue by peiniwan** [codyer/ElegantBus#16]
报错信息
 What went wrong:
A problem occurred configuring root project 'ElegantBus'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.checkerframework:checker-qual:3.5.0.
     Required by:
         project : > com.android.application:com.android.application.gradle.plugin:7.2.2 > com.android.tools.build:gradle:7.2.2 > org.tensorflow:tensorflow-lite-metadata:0.1.0-rc2
      > Could not resolve org.checkerframework:checker-qual:3.5.0.
         > Could not get resource 'https://jitpack.io/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.pom'.
            > Could not HEAD 'https://jitpack.io/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.pom'.
               > Read timed out
   > Could not resolve org.checkerframework:checker-qual:3.5.0.
     Required by:
         project : > com.android.application:com.android.application.gradle.plugin:7.2.2 > com.android.tools.build:gradle:7.2.2 > com.android.tools:sdk-common:30.2.2 > com.google.guava:guava:30.1-jre
      > Could not resolve org.checkerframework:checker-qual:3.5.0.
         > Could not get resource 'https://jitpack.io/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.pom'.
            > Could not HEAD 'https://jitpack.io/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.pom'.
               > Read timed out

**Comment by codyer** [comment]
> 报错信息 What went wrong: A problem occurred configuring root project 'ElegantBus'.
> 
> > Could not resolve all files for configuration ':classpath'.
> > Could not resolve org.checkerframework:checker-qual:3.5.0.
> > Required by:
> > project : > com.android.application:com.android.application.gradle.plugin:7.2.2 > com.android.tools.build:gradle:7.2.2 > org.tensorflow:tensorflow-lite-metadata:0.1.0-rc2
> > > Could not resolve org.checkerframework:checker-qual:3.5.0.
> > > Could not get resource 'https://jitpack.io/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.pom'.
> > > Could not HEAD 'https://jitpack.io/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.pom'.
> > > Read timed out
> > Could not resolve org.checkerframework:checker-qual:3.5.0.
> > Required by:
> > project : > com.android.application:com.android.application.gradle.plugin:7.2.2 > com.android.tools.build:gradle:7.2.2 > com.android.tools:sdk-common:30.2.2 > com.google.guava:guava:30.1-jre
> > > Could not resolve org.checkerframework:checker-qual:3.5.0.
> > > Could not get resource 'https://jitpack.io/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.pom'.
> > > Could not HEAD 'https://jitpack.io/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.pom'.
> > > Read timed out

这个和你本地环境有关，和项目关系不大，可以check下网络，gradle 版本等

**Comment by peiniwan** [comment]
def version = "2.0.0"
    implementation "com.gitee.codyer.ElegantBus:core:$version"

为什么我依赖下不下来

> > 报错信息 What went wrong: A problem occurred configuring root project 'ElegantBus'.
> > > Could not resolve all files for configuration ':classpath'.
> > > Could not resolve org.checkerframework:checker-qual:3.5.0.
> > > Required by:
> > > project : > com.android.application:com.android.application.gradle.plugin:7.2.2 > com.android.tools.build:gradle:7.2.2 > org.tensorflow:tensorflow-lite-metadata:0.1.0-rc2
> > > > Could not resolve org.checkerframework:checker-qual:3.5.0.
> > > > Could not get resource 'https://jitpack.io/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.pom'.
> > > > Could not HEAD 'https://jitpack.io/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.pom'.
> > > > Read timed out
> > > > Could not resolve org.checkerframework:checker-qual:3.5.0.
> > > > Required by:
> > > > project : > com.android.application:com.android.application.gradle.plugin:7.2.2 > com.android.tools.build:gradle:7.2.2 > com.android.tools:sdk-common:30.2.2 > com.google.guava:guava:30.1-jre
> > > > Could not resolve org.checkerframework:checker-qual:3.5.0.
> > > > Could not get resource 'https://jitpack.io/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.pom'.
> > > > Could not HEAD 'https://jitpack.io/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.pom'.
> > > > Read timed out
> 
> 这个和你本地环境有关，和项目关系不大，可以check下网络，gradle 版本等

**Comment by codyer** [comment]
> ```
> def version = "2.0.0"
> implementation "com.gitee.codyer.ElegantBus:core:$version"
> ```
> 
> 为什么我依赖下不下来
> 
> > > 报错信息 What went wrong: A problem occurred configuring root project 'ElegantBus'.
> > > > Could not resolve all files for configuration ':classpath'.
> > > > Could not resolve org.checkerframework:checker-qual:3.5.0.
> > > > Required by:
> > > > project : > com.android.application:com.android.application.gradle.plugin:7.2.2 > com.android.tools.build:gradle:7.2.2 > org.tensorflow:tensorflow-lite-metadata:0.1.0-rc2
> > > > > Could not resolve org.checkerframework:checker-qual:3.5.0.
> > > > > Could not get resource 'https://jitpack.io/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.pom'.
> > > > > Could not HEAD 'https://jitpack.io/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.pom'.
> > > > > Read timed out
> > > > > Could not resolve org.checkerframework:checker-qual:3.5.0.
> > > > > Required by:
> > > > > project : > com.android.application:com.android.application.gradle.plugin:7.2.2 > com.android.tools.build:gradle:7.2.2 > com.android.tools:sdk-common:30.2.2 > com.google.guava:guava:30.1-jre
> > > > > Could not resolve org.checkerframework:checker-qual:3.5.0.
> > > > > Could not get resource 'https://jitpack.io/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.pom'.
> > > > > Could not HEAD 'https://jitpack.io/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.pom'.
> > > > > Read timed out
> > 
> > 
> > 这个和你本地环境有关，和项目关系不大，可以check下网络，gradle 版本等

你这个是以来的gitee仓库的，如果你配置的是github，需要换成github的仓库

**Comment by codyer** [comment]
implementation "com.github.codyer.ElegantBus:core:$version" // 不需要跨进程时使用

**Comment by peiniwan** [comment]
> implementation "com.github.codyer.ElegantBus:core:$version" // 不需要跨进程时使用
另一个页面
   ElegantBus.getDefault(
            "WebViewScope", "eventString2",
            String::class.java, true
        ).post("erwqrqwrwe")

fragment
  ElegantBus.getDefault("WebViewScope", "eventString2", java.lang.String.class, true).observe(this,new ObserverWrapper<String>() {
            @Override
            public void onChanged(@Nullable String value) {
                //为什么这个执行了？
                Log.d("WebViewInterceptor", "666"+value);
                ToastUtils.show(value);
            }
        });

为什么我的fragment还没显示就能收到数据
