### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by peiniwan** [codyer/ElegantBus#18]
D/LeakCanary: ​
        ┬───
        │ GC Root: Local variable in native code
        │
        ├─ dalvik.system.PathClassLoader instance
        │    Leaking: NO (BusFactory$InstanceHolder↓ is not leaking and A ClassLoader is never leaking)
        │    ↓ ClassLoader.runtimeInternalObjects
        ├─ java.lang.Object[] array
        │    Leaking: NO (BusFactory$InstanceHolder↓ is not leaking)
        │    ↓ Object[2822]
        ├─ cody.bus.BusFactory$InstanceHolder class
    │    Leaking: NO (a class is never leaking)
        │    ↓ static BusFactory$InstanceHolder.INSTANCE
        │                                       ~~~~~~~~
        ├─ cody.bus.BusFactory instance
        │    Leaking: UNKNOWN
        │    Retaining 284.9 kB in 3525 objects
        │    ↓ BusFactory.mGroupBus
        │                 ~~~~~~~~~
        ├─ java.util.HashMap instance
        │    Leaking: UNKNOWN
        │    Retaining 284.6 kB in 3511 objects
        │    ↓ HashMap["WebScope"]
        │             ~~~~~~~~~~~~
        ├─ cody.bus.BusFactory$EventGroupHolder instance
        │    Leaking: UNKNOWN
        │    Retaining 284.5 kB in 3508 objects
        │    ↓ BusFactory$EventGroupHolder.eventBus
        │                                  ~~~~~~~~
        ├─ java.util.HashMap instance
        │    Leaking: UNKNOWN
        │    Retaining 284.4 kB in 3507 objects
        │    ↓ HashMap["jsFileBeanEvent"]
        │             ~~~~~~~~~~~~~~~~~~~
        ├─ cody.bus.ActiveLiveDataWrapper instance
        │    Leaking: UNKNOWN
        │    Retaining 283.0 kB in 3467 objects
        │    ↓ ActiveLiveDataWrapper.mObserverWrappers
        │                            ~~~~~~~~~~~~~~~~~
        ├─ java.util.ArrayList instance
        │    Leaking: UNKNOWN
        │    Retaining 282.6 kB in 3456 objects
        │    ↓ ArrayList[0]
        │               ~~~
        ├─  common.web.controller.DsFileJsController$fileBeanObserver$1 instance
        │    Leaking: UNKNOWN
        │    Retaining 282.6 kB in 3454 objects
        │    Anonymous subclass of cody.bus.ObserverWrapper
        │    owner instance of  common.web.DsWebViewActivity with mDestroyed = true
        │    ↓ ObserverWrapper.owner
        │                      ~~~~~
        ╰→  common.web.DsWebViewActivity instance
        ​     Leaking: YES (ObjectWatcher was watching this because DsWebViewActivity received
        ​     Activity#onDestroy() callback and Activity#mDestroyed is true)
        ​     Retaining 201.6 kB in 3032 objects
        ​     key = fd540911-cba8-4cf2-ad7b-15e4bb69f374
        ​     watchDurationMillis = 15036
        ​     retainedDurationMillis = 10035
        ​     mContext instance of .DsWebViewActivity with mDestroyed = true
        ​     mApplication instance of XrsApplication
        ​     mBase instance of android.app.ContextImpl

        METADATA

        Build.VERSION.SDK_INT: 30
        Build.MANUFACTURER: Xiaomi
        LeakCanary version: 2.8.1
        Stats: LruCache[maxSize=3000,hits=73106,misses=195066,hitRate=27%]
        RandomAccess[bytes=10570353,reads=195066,travel=128046196885,range=37842294,size=55983256]
        Analysis duration: 15869 ms

在页面出去的时候已经调用了：
     WebScopeBus.jsFileBeanEvent().removeObserver(fileBeanObserver)
     WebScopeBus.jsFileBeanEvent().removeObservers(activity)

**Comment by likepoem-oops** [comment]
您好，请问这个问题是怎么解决的呢
