### ISSUE TITLE
 Caused by: java.lang.SecurityException: Not allowed to bind to service Intent { act=android.intent.action.MAIN cmp=/cody.bus.ProcessManagerService }

### ISSUE THREAD

**Issue by BBNO** [codyer/ElegantBus#19]
作者你好，这个库支持其他APP绑定ProcessManagerService这个服务吗？

**Comment by codyer** [comment]
> 作者你好，这个库支持其他APP绑定ProcessManagerService这个服务吗？

你需要在manifest文件中申请权限 可以参考一下Elegant Example工程

**Comment by BBNO** [comment]
Elegant Example工程 中没有看到对应的例子，也没看到在manifest文件中申请权限

**Comment by BBNO** [comment]
@codyer 我有在manifest文件中申请了权限，还是报上面那个错：
`<uses-permission android:name="com.xxxx.xxxx.bus_ipc.PERMISSION" />`

**Comment by BBNO** [comment]
@codyer 我有在manifest文件中申请了权限，还是报上面那个错：
`<uses-permission android:name="com.xxxx.xxxx.bus_ipc.PERMISSION" />`

**Comment by codyer** [comment]
> @codyer 我有在manifest文件中申请了权限，还是报上面那个错： `<uses-permission android:name="com.xxxx.xxxx.bus_ipc.PERMISSION" />`

<img width="865" alt="image" src="https://github.com/codyer/ElegantBus/assets/13249902/9d9db232-1b5e-4210-b63f-318e02606d96">
你详细描述下你使用的场景吧，正常来说不需要自己去绑定ProcessManagerService，直接设置成同一个组就行的，但是要注意上面的权限问题。
