### ISSUE TITLE
moudle依赖

### ISSUE THREAD

**Issue by Cai-Go** [codyer/ElegantBus#2]
为什么把 lib-core 和 lib 添加为 moudle 时，编译一直失败
![image](https://user-images.githubusercontent.com/7565399/87243027-e79fba80-c464-11ea-90fe-10a6eba2c7d5.png)

**Comment by codyer** [comment]
lib-core和lib的版本号是什么？初步看应该是APT自动生成失败，没有生成对应的MyAppEventBus

**Comment by codyer** [comment]
> 为什么把 lib-core 和 lib 添加为 moudle 时，编译一直失败
> 
> ![image](https://user-images.githubusercontent.com/7565399/87243027-e79fba80-c464-11ea-90fe-10a6eba2c7d5.png)
> 
> 

lib-core和lib的版本号是什么？初步看应该是APT自动生成失败，没有生成对应的MyAppEventBus

**Comment by Cai-Go** [comment]
> > 为什么把 lib-core 和 lib 添加为 moudle 时，编译一直失败
> > ![image](https://user-images.githubusercontent.com/7565399/87243027-e79fba80-c464-11ea-90fe-10a6eba2c7d5.png)
> 
> lib-core和lib的版本号是什么？初步看应该是APT自动生成失败，没有生成对应的MyAppEventBus

2.0.0 的复制过去的。compiler 这个需要么？我试着放进去也是失败的

**Comment by codyer** [comment]
> > > 为什么把 lib-core 和 lib 添加为 moudle 时，编译一直失败
> > > ![image](https://user-images.githubusercontent.com/7565399/87243027-e79fba80-c464-11ea-90fe-10a6eba2c7d5.png)
> > 
> > 
> > lib-core和lib的版本号是什么？初步看应该是APT自动生成失败，没有生成对应的MyAppEventBus
> 
> 2.0.0 的复制过去的。compiler 这个需要么？我试着放进去也是失败的

你可以详细说明一下情况吗？
比如你做了什么配置，你想做什么？
你可以先参考一下 ElehantBus-Example 先单独使用，排除一些多余因素。

**Comment by Cai-Go** [comment]
> > > > 为什么把 lib-core 和 lib 添加为 moudle 时，编译一直失败
> > > > ![image](https://user-images.githubusercontent.com/7565399/87243027-e79fba80-c464-11ea-90fe-10a6eba2c7d5.png)
> > > 
> > > 
> > > lib-core和lib的版本号是什么？初步看应该是APT自动生成失败，没有生成对应的MyAppEventBus
> > 
> > 
> > 2.0.0 的复制过去的。compiler 这个需要么？我试着放进去也是失败的
> 
> 你可以详细说明一下情况吗？
> 比如你做了什么配置，你想做什么？
> 你可以先参考一下 ElehantBus-Example 先单独使用，排除一些多余因素。

就是把 lib-core 和 lib 添加为 moudle 来用
![image](https://user-images.githubusercontent.com/7565399/87246947-4bd17700-c483-11ea-8a1a-9e0b3f94ffb9.png)

**Comment by codyer** [comment]
> > > > > 为什么把 lib-core 和 lib 添加为 moudle 时，编译一直失败
> 
> > > > > ![image](https://user-images.githubusercontent.com/7565399/87243027-e79fba80-c464-11ea-90fe-10a6eba2c7d5.png)
> 
> > > > 
> 
> > > > 
> 
> > > > lib-core和lib的版本号是什么？初步看应该是APT自动生成失败，没有生成对应的MyAppEventBus
> 
> > > 
> 
> > > 
> 
> > > 2.0.0 的复制过去的。compiler 这个需要么？我试着放进去也是失败的
> 
> > 
> 
> > 你可以详细说明一下情况吗？
> 
> > 比如你做了什么配置，你想做什么？
> 
> > 你可以先参考一下 ElehantBus-Example 先单独使用，排除一些多余因素。
> 
> 
> 
> 就是把 lib-core 和 lib 添加为 moudle 来用
> 
> ![image](https://user-images.githubusercontent.com/7565399/87246947-4bd17700-c483-11ea-8a1a-9e0b3f94ffb9.png)
> 
> 

不明白为什么要这样用，如果要使用component项目里面的模块，可以参考 https://jitpack.io/#codyer/component
直接通过dependence的方式引入就可以了，component里面每个module都可以单独使用的，如果你想考过来用，就需要你参考一下component项目里面的配置了。

**Comment by codyer** [comment]
> 为什么把 lib-core 和 lib 添加为 moudle 时，编译一直失败
> 
> ![image](https://user-images.githubusercontent.com/7565399/87243027-e79fba80-c464-11ea-90fe-10a6eba2c7d5.png)
> 
> 

后续如果还有问题的话，你可以尝试把精简的工程发给我，我下周可以帮你看看，这周实在太忙了

**Comment by wuzhaohui026** [comment]
好
