### ISSUE TITLE
bugly 报 anr

### ISSUE THREAD

**Issue by liuyu92-tal** [codyer/ElegantBus#20]
# main(1)

ANR_EXCEPTION

AppFreeze!

解析原始
1
android.os.BinderProxy.transactNative(Native Method)
2
android.os.BinderProxy.transact(Binder.java:1154)
3
cody.bus.IProcessManager$Stub$Proxy.postToService(IProcessManager.java:208)
4
cody.bus.MultiProcessImpl.postToService(MultiProcessImpl.java:98)
5
cody.bus.ActiveLiveDataWrapper.post(ActiveLiveDataWrapper.java:103)
6
xxx.cache.UserManager.updateUserInfo(UserManager.java:206)

206行我对应的代码是：            
WebScopeBus.loginUserIdEvent().post(new LoginUserIdEvent(mCurrentUserInfo.getUserid()));

您知道是什么原因吗

**Comment by codyer** [comment]
之前没有做线程切换，json转换都是主线程执行的，所以有几率会发生ANR情况，可以使用3.1.3版本，对跨线程做了优化。

**Comment by liuyu92-tal** [comment]
> 之前没有做线路切换，json转切换都是主线路执行的，所以有几次会发生ANR情况，可以使用3.1.3版本，对跨线路做优化。

更新了3.1.3后编译报错：Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by liuyu92-tal** [comment]
> > 之前没有做线路切换，json转切换都是主线路执行的，所以有几次会发生ANR情况，可以使用3.1.3版本，对跨线路做优化。
> 
> 更新了3.1.3后编译报错：Execution failed for task ':app:processDebugManifest'.
> 
> > Manifest merger failed with multiple errors, see logs

配上这个就好了：
```
BUS_SUPPORT_MULTI_APP  : false,
BUS_MAIN_APPLICATION_ID: rootProject.ext.android.applicationId
```
可是新版有个问题：通知栏会一直常驻一个BusService的通知，可以去掉这个通知吗？

**Comment by codyer** [comment]
目前暂时不支持去掉这个service

**Comment by liuyu92-tal** [comment]
> 目前暂时不支持去掉这个service

service可以不去掉，我是指改成了前台服务，通知栏一直有个通知，显示圆圈和BusService的通知，会使用户很困惑，可以像以前改成一个普通的服务吗

**Comment by codyer** [comment]
> 

目前3.2.0版本支持去掉通知栏，同时添加了contentProvider方式作为事件中心，事件更不容易丢失，建议使用
主App和子App引用有部分区别，具体参见说明文档
