### ISSUE TITLE
多个APP 跨进程

### ISSUE THREAD

**Issue by strong-zz** [codyer/ElegantBus#21]
大佬，能不能专门出一个简易版的多个APP跨进程的Demo，您出的那个Demo，不太能理解，怎么看都APP内通信

**Comment by codyer** [comment]
> 大佬，能不能专门出一个简易版的多个APP跨进程的Demo，您出的那个Demo，不太能理解，怎么看都APP内通信
你可以直接在多个APP中使用，就和在同一个APP中使用一样，demo通过不同的build varaint 编译出来的才是支持多app的，
可以看看gradle脚本，里面做了不同包名指定，因此是多个app，虽然界面一样
