### ISSUE TITLE
您好提供一个getvalue方法是否合理

### ISSUE THREAD

**Issue by zguop** [codyer/ElegantBus#4]

**Comment by codyer** [comment]
可以描述一下你的使用场景吗？

**Comment by codyer** [comment]
> _No description provided._

其实在刚开始的版本中是有getValue方法的，同时还有initValue方法，这两个方法是成套出现的，后面经过实际使用和综合考虑去掉了这两个方法，因为大部分情况可以使用事件的粘性特性进行替换，而且getValue很容易获得Null值，因为忘记初始化，或者初始化时机不对，因此getValue的存在本身不太合理。

**Comment by zguop** [comment]
本身就是一个LiveData ， 我觉得可以有

我这边是用它去计数 通知到各个地方显示，getValue + newNum = count 发送出去

**Comment by codyer** [comment]
> 本身就是一个LiveData ， 我觉得可以有
> 
> 我这边是用它去计数 通知到各个地方显示，getValue + newNum = count 发送出去

这种场景我也遇到过，其实oldValue从LiveData中实时获取不太可靠，可以自己业务保存oldValue；
oldValue的初始值可以通过粘性获取。
eg：
mOldValue = 0；
TestScopeBus.eventInt().observe(owner, new ObserverWrapper<Integer>(true) {
	@Override
	public void onChanged(final Integer oldValue) {
		...
mOldValue = oldValue；
这个时候获取的其实就是oldValue，可以将其保存到全局变量
	}
});
post（mOldValue + step）

**Comment by codyer** [comment]
> 本身就是一个LiveData ， 我觉得可以有
> 
> 我这边是用它去计数 通知到各个地方显示，getValue + newNum = count 发送出去

当然，如果你还是愿意这么用的话，可以提供一个getValue，2.2.0可以使用

**Comment by zguop** [comment]
感谢作者
