### ISSUE TITLE
Service 如何开启监听

### ISSUE THREAD

**Issue by anheiqq** [codyer/ElegantBus#6]
请问一下 如何在Service里开启监听， 是否支持呢？

**Comment by anheiqq** [comment]
使用常驻事件  还是 继承 LifecycleService  好一些

**Comment by codyer** [comment]
> 使用常驻事件 还是 继承 LifecycleService 好一些

看你的需求了，常驻事件不依赖于 LifecycleOwner，Service也可以用；
因为 LifecycleService 实现了LifecycleOwner接口，所以也可以用于非常驻事件。
