### ISSUE TITLE
建议提供或者暴露出一个工具类,动态进行初始化,类似于LiveEventBus那样有一个APPUtil工具类一样可以进行初始化.

### ISSUE THREAD

**Issue by Chills719** [codyer/ElegantBus#8]
//初始化LiveData
  AppUtils.init(application);

**Comment by codyer** [comment]
并不需要初始化为什么要有这样的工具类呢？
还有你说遇到引入当子模块的问题到底是什么问题呢？
建议仔细查看使用文档。

以上
谢谢

**Comment by Chills719** [comment]
你好,是这样的,因为我目前的项目是使用了Xposed模块,当前工程和Xposed模块中hook的app当属2个进程,所以就需要用到多进程通讯,但是在外壳项目中通过依赖gradle文件自动进行了初始化相关的操作是可以使用的,但是我还需要在Xposed模块中也进行使用,但是确无法像当前项目那样进行gradle依赖,所以就无法进行初始化,LIveDataBus的话,是暴露出了一个AppUtils工具类可以手动在Application中进行初始化,但是其采用的跨进程通讯方式仍然是广播机制,贵项目的话目前我想在XPosed模块中手动进行相关类的初始化,也无法进行,故提出上述问题.

**Comment by Chills719** [comment]
XPosed模块是写在我当前工程目录里面的,所以外层项目通过依赖Gradle文件可以正常进行代码层面的操作,但是Xposed模块当属另外一个独立进程,所以外层项目所依赖的Gradle文件无法生效.

**Comment by codyer** [comment]
> XPosed模块是写在我当前工程目录里面的,所以外层项目通过依赖Gradle文件可以正常进行代码层面的操作,但是Xposed模块当属另外一个独立进程,所以外层项目所依赖的Gradle文件无法生效.

你可以提供一个最小的demo工程吗？
不是很理解你的问题出在哪里。
你可以给我发一个最小的demo，把你需要发送数据的地方和接收数据的地方伪代码或者注释一下，我可以帮你看看。

可以加我微信：codyer
或者邮件联系：kadierxu@sina.com
